### PR TITLE
Mermaid chart integration

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
Implementing rendering of mermaid charts.

- panning and mouse wheel zooming

---

---
- examples:
  - >image
  - >image
  - image

- pretty clean rendering in realtime:
vokoscreenNG-2023-08-20_20-17-27 (1) (1) (1)

- Usually ChatGPT knows to respond in mermaid syntax *(although it does sometimes hallucinate about mermaids 🧜)*. 
  Lowering the temperature helps, and it sometimes needs very specific instructions too.

 Mermaid is even ubiquitous enough that Github natively supports it:
  ```mermaid
  pie title Causes of Death Worldwide
    "Cardiovascular diseases" : 31
    "Cancer" : 17
    "Respiratory diseases" : 7
    "Lower respiratory infections" : 5
    "Dementia" : 7
    "Digestive diseases" : 3
    "Neonatal disorders" : 2
    "Diabetes" : 3
    "Kidney disease" : 2
    "Liver diseases" : 2
    "Other causes" : 21
```

### CODE REVIEW

**Comment by jackschedel** [comment]
wow this is so cool! working on fixing the deps for you.

**Comment by jackschedel** [comment]
need to run `yarn add mermaid` and commit to fix the build error.

However, even when doing this, I am getting a weird Electron-only error that I don't get with the web version. None of the app loads, and it throws the error:

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'prototype')
```
jf = function(e, t, n) {
    e.prototype = t.prototype = n,
    n.constructor = e
}
 ```

~~Edit: might not have been electron only, maybe it's any chats with code blocks and it just happened that my electron was open to one. Speculation while in bed here, will test tomorrow.~~

**Comment by jackschedel** [comment]
@cheeseonamonkey leaving you to work on fixing this error in the Electron version. I tried using SourceMaps to find what TS file/line is causing this with no luck. That might mean its somewhere within a library call and we somehow need to get the stack trace. Lmk if you have this issue on the Electron App too or if its some edge case that happens to show up on my loaded chats.

**Comment by cheeseonamonkey** [comment]
I hadn't tested on the electron app - I'll see what I can do!

**Comment by jackschedel** [comment]
@cheeseonamonkey `package-lock.json` shouldn't need to be in gitignore since we're using `yarn` for dependency installs, which doesn't generate `package-lock.json` but rather `yarn.lock`. Your `package-lock.json` is probably a remnant of accidentally manually running `npm install`. You can safely delete your local `package-lock.json` and keep it out of the gitignore. 

Note that you still need to do a commit with `yarn add mermaid` to at least get the checks passing (the Electron issue is during init at runtime tho,  so just bc the checks pass doesn't mean it's fixed)

**Comment by cheeseonamonkey** [comment]
```
jf = function(e, t, n) {
    e.prototype = t.prototype = n,
    n.constructor = e
}
```

I got this at first, too - but I got electron building successfully by running `npm run electron` _(after building)_?

I think I've cleared it up maybe?

**Comment by cheeseonamonkey** [comment]
I think all of the [conflicts](https://github.com/jackschedel/KoalaClient/pull/79/conflicts) can use incoming changes also.

**Comment by jackschedel** [comment]
doing `npm run electron` is basically just running `npm run dev` inside of an electron window rather than a browser. I just tried doing `npm run build` and opening the built index.html file (disable CORS in dist directory in browser launch flags https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome?noredirect=1&lq=1) and got the same error.  This means that the issue isn't just Electron, it's any static build (i.e. it would happen if deployed to the website too).

**Comment by jackschedel** [comment]
@cheeseonamonkey converting to a draft, mark as ready for review once you fix the static build issue

**Comment by cheeseonamonkey** [comment]
@jackschedel 
> (disable CORS in dist directory in browser launch flags)

That is a super useful trick!  :sweat_smile:

But I think I've corrected the issue by downgrading the Mermaid.js version to `~9.4` _(from `^10.2`)_ to fix some package compatibility issue.

 _(I think with the compatibility conflict was with React, although I'm not entirely sure)_.

**Comment by jackschedel** [comment]
Thanks for fixing this, working now. I'll try to work on the merge conflicts tn. Classes have started back up for me so expect slower turnaround times xD

**Pull request merged**
