### PR TITLE
Model config

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
Mostly refactoring the new model config stuff, without changing anything:
  
- extracted a component for each model's config UI:
  f6fae3c308e705c2ec1e5ea6e266a44f5d6e7b0a
  
- refactored api.ts:
  0cc444e5da7f34a49f464b22551f3858630b90de

- add titles to each input fields *(those HTML hover-popup labels)*

- added a fetch to the openai API to get all available models *(not yet implemented)*:
  b290a8786c0658ae8de99c3b98fae25e2f7573e1

### CODE REVIEW

**Comment by jackschedel** [comment]
Hi, thanks for the PR.
Can you run the prettier autoformat `yarn format` and commit it so I can get a better diff view?
I think many of your api.ts spacing refactors with the `onChange` inlines will be auto-formatted out.

**Comment by jackschedel** [comment]
Also, please remove the unused variables that ESLint is warning about.

**Comment by cheeseonamonkey** [comment]
Oh yes, I see what you mean. I can clean it up a bit.

The original intent was to load the models dynamically from the OpenAI API, but some refactoring instincts kicked in first :sweat_smile:

**Comment by jackschedel** [comment]
@cheeseonamonkey Hi, while I initially did some brief testing and it seemed to work, after using it myself I've encountered issues where new model definitions do not save. I have reverted the PR. If you wish for these changes, fix the issues and make a new PR.

**Pull request merged**
